### Apps Cleaning

In [2]:
import numpy as np
import pandas as pd

In [50]:
g_data = pd.read_csv("apps.csv")
g_data.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [51]:
g_data.drop("Unnamed: 0", axis = 1, inplace = True)
g_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [52]:
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   object
 6   Type            9659 non-null   object
 7   Price           9659 non-null   object
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 981.1+ KB

In [53]:
g_data.isnull().sum()

App                  0
Category             0
Rating            1463
Reviews              0
Size              1227
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [54]:
g_data.Price.value_counts()

Price
0          8903
$0.99       145
$2.99       124
$1.99        73
$4.99        70
           ...
$18.99        1
$389.99       1
$19.90        1
$1.75         1
$1.04         1
Name: count, Length: 92, dtype: int64

In [55]:
g_data.Price = g_data.Price.apply(lambda x: str(x).replace("$","") if "$" in str(x) else str(x))
g_data.Price = g_data.Price.apply(lambda x: float(x))
g_data.Price.value_counts()

Price
0.00      8903
0.99       145
2.99       124
1.99        73
4.99        70
          ...
18.99        1
389.99       1
19.90        1
1.75         1
1.04         1
Name: count, Length: 92, dtype: int64

In [56]:
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   object
 6   Type            9659 non-null   object
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 981.1+ KB

In [57]:
g_data.Installs.value_counts()

Installs
1,000,000+        1417
100,000+          1112
10,000+           1031
10,000,000+        937
1,000+             888
100+               710
5,000,000+         607
500,000+           505
50,000+            469
5,000+             468
10+                385
500+               328
50+                204
50,000,000+        202
100,000,000+       188
5+                  82
1+                  67
500,000,000+        24
1,000,000,000+      20
0+                  14
0                    1
Name: count, dtype: int64

In [58]:
g_data.Installs = g_data.Installs.apply(lambda x: str(x).replace("+","") if "+" in str(x) else str(x))
g_data.Installs = g_data.Installs.apply(lambda x: str(x).replace(",","") if "," in str(x) else str(x))
g_data.Installs = g_data.Installs.apply(lambda x: int(x))
g_data.Installs.value_counts()

Installs
1000000       1417
100000        1112
10000         1031
10000000       937
1000           888
100            710
5000000        607
500000         505
50000          469
5000           468
10             385
500            328
50             204
50000000       202
100000000      188
5               82
1               67
500000000       24
1000000000      20
0               15
Name: count, dtype: int64

In [59]:
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9659 non-null   object
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 981.1+ KB

In [60]:
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9659 non-null   object
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 981.1+ KB

In [61]:
# Replace spaces with underscores in column names
g_data.columns = g_data.columns.str.replace(' ', '_')

# Display the modified DataFrame
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9659 non-null   object
 7   Price           9659 non-null   float64
 8   Content_Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last_Updated    9659 non-null   object
 11  Current_Ver     9651 non-null   object
 12  Android_Ver     9657 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 981.1+ KB

In [62]:
import re
 
pattern = r'[^a-zA-Z0-9\s.,!?\':-]' 
 
mask1 = g_data['App'].str.contains(pattern, regex=True)
mask12 = g_data['Current_Ver'].str.contains(pattern, regex=True)

 
g_data2 = g_data[~(mask1 | mask12)]
g_data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7870 entries, 1 to 9657
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             7870 non-null   object
 1   Category        7870 non-null   object
 2   Rating          6592 non-null   float64
 3   Reviews         7870 non-null   int64
 4   Size            6952 non-null   float64
 5   Installs        7870 non-null   int64
 6   Type            7870 non-null   object
 7   Price           7870 non-null   float64
 8   Content_Rating  7870 non-null   object
 9   Genres          7870 non-null   object
 10  Last_Updated    7870 non-null   object
 11  Current_Ver     7862 non-null   object
 12  Android_Ver     7870 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 860.8+ KB

In [63]:
null_counts = g_data2.isnull().sum()
print("Null Counts:")
print(null_counts)

duplicates = g_data2.duplicated().sum()
print("\nNumber of Duplicates:", duplicates)

g_data2.info()

Null Counts:
App                  0
Category             0
Rating            1278
Reviews              0
Size               918
Installs             0
Type                 0
Price                0
Content_Rating       0
Genres               0
Last_Updated         0
Current_Ver          8
Android_Ver          0
dtype: int64

Number of Duplicates: 0
<class 'pandas.core.frame.DataFrame'>
Index: 7870 entries, 1 to 9657
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             7870 non-null   object
 1   Category        7870 non-null   object
 2   Rating          6592 non-null   float64
 3   Reviews         7870 non-null   int64
 4   Size            6952 non-null   float64
 5   Installs        7870 non-null   int64
 6   Type            7870 non-null   object
 7   Price           7870 non-null   float64
 8   Content_Rating  7870 non-null   object
 9   Genres          7870 non-null   object
 10  Last_Updated    7870 non-null   object
 11  Current_Ver     7862 non-null   object
 12  Android_Ver     7870 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 860.8+ KB

In [64]:
g_data2 = g_data2.dropna()

g_data2.reset_index(drop=True, inplace=True)

g_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5720 entries, 0 to 5719
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             5720 non-null   object
 1   Category        5720 non-null   object
 2   Rating          5720 non-null   float64
 3   Reviews         5720 non-null   int64
 4   Size            5720 non-null   float64
 5   Installs        5720 non-null   int64
 6   Type            5720 non-null   object
 7   Price           5720 non-null   float64
 8   Content_Rating  5720 non-null   object
 9   Genres          5720 non-null   object
 10  Last_Updated    5720 non-null   object
 11  Current_Ver     5720 non-null   object
 12  Android_Ver     5720 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 581.1+ KB

In [65]:
output_csv_path = 'cleaned_apps_f.csv'


# Write the DataFrame to a CSV file
g_data2.to_csv(output_csv_path, index=False)

### Reviews cleaning

In [3]:
g_data = pd.read_csv("user_reviews.csv")
g_data.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [5]:
g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [6]:
g_data.isnull().sum()

App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

In [7]:
null_counts = g_data.isnull().sum()
print("Null Counts:")
print(null_counts)

duplicates = g_data.duplicated().sum()
print("\nNumber of Duplicates:", duplicates)

g_data.info()

Null Counts:
App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

Number of Duplicates: 33616
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [8]:
g_data = g_data.dropna()

g_data.reset_index(drop=True, inplace=True)

g_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37427 entries, 0 to 37426
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     37427 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37427 non-null  object
 3   Sentiment_Polarity      37427 non-null  float64
 4   Sentiment_Subjectivity  37427 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.4+ MB

In [10]:
import re
 
pattern = r'[^a-zA-Z0-9\s.,!?\':-]'  
mask1 = g_data['App'].str.contains(pattern, regex=True)
mask2 = g_data['Translated_Review'].str.contains(pattern, regex=True)
mask3 = g_data['Sentiment'].str.contains(pattern, regex=True)

g_data2 = g_data[~(mask1 | mask2 | mask3)]
g_data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24599 entries, 1 to 37372
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     24599 non-null  object
 1   Translated_Review       24599 non-null  object
 2   Sentiment               24599 non-null  object
 3   Sentiment_Polarity      24599 non-null  float64
 4   Sentiment_Subjectivity  24599 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.1+ MB

In [12]:
g_data2['Sentiment_Polarity'] = g_data2['Sentiment_Polarity'].round(2)
g_data2['Sentiment_Subjectivity'] = g_data2['Sentiment_Subjectivity'].round(2)

g_data2.head(20)

/var/folders/g1/59712b0d2tn39h05vhxzvm8m0000gn/T/ipykernel_67133/2718860413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g_data2['Sentiment_Polarity'] = g_data2['Sentiment_Polarity'].round(2)
/var/folders/g1/59712b0d2tn39h05vhxzvm8m0000gn/T/ipykernel_67133/2718860413.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g_data2['Sentiment_Subjectivity'] = g_data2['Sentiment_Subjectivity'].round(2)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.29
2,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.88
3,10 Best Foods for You,Best idea us,Positive,1.00,0.30
4,10 Best Foods for You,Best way,Positive,1.00,0.30
5,10 Best Foods for You,Amazing,Positive,0.60,0.90
6,10 Best Foods for You,"Looking forward app,",Neutral,0.00,0.00
7,10 Best Foods for You,It helpful site ! It help foods get !,Neutral,0.00,0.00
8,10 Best Foods for You,good you.,Positive,0.70,0.60
9,10 Best Foods for You,Useful information The amount spelling errors ...,Positive,0.20,0.10
11,10 Best Foods for You,Greatest ever Completely awesome maintain heal...,Positive,0.99,0.87
12,10 Best Foods for You,Good health...... Good health first priority.....,Positive,0.55,0.51
14,10 Best Foods for You,"Mrs sunita bhati I thankful developers,to make...",Positive,0.60,0.67
15,10 Best Foods for You,Very Useful in diabetes age 30. I need control...,Positive,0.30,0.10
16,10 Best Foods for You,One greatest apps.,Positive,1.00,1.00
17,10 Best Foods for You,good nice,Positive,0.65,0.80
18,10 Best Foods for You,Healthy Really helped,Positive,0.35,0.35
19,10 Best Foods for You,God health,Neutral,0.00,0.00
20,10 Best Foods for You,HEALTH SHOULD ALWAYS BE TOP PRIORITY. !!. ON M...,Positive,0.78,0.50
21,10 Best Foods for You,An excellent A useful,Positive,0.65,0.50
22,10 Best Foods for You,I found lot wealth form health...,Neutral,0.00,0.00

In [13]:
g_data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24599 entries, 1 to 37372
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     24599 non-null  object
 1   Translated_Review       24599 non-null  object
 2   Sentiment               24599 non-null  object
 3   Sentiment_Polarity      24599 non-null  float64
 4   Sentiment_Subjectivity  24599 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.1+ MB

In [14]:
output_csv_path = 'cleaned_reviews_f.csv'


g_data2.to_csv(output_csv_path, index=False)